import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import fs from 'fs';
import HEART from '../public/assets/HEART.png'
import logo1 from '../public/assets/logo1.png'
import path from "path";


const inter = Inter({ subsets: ["latin"] });

export default function HomePage({recipe}) {
  return (
    <>
      <Head>
        <title>The Recipe Room</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="assets/logo1.png" />
     
      </Head>
      <section className="section1">
      <div className="container"> 
        <h1 className="hometitle">Top 10 Recipes</h1>
        </div>


        <section className="recipe-section">
            {recipe && recipe.slice(0,5).map((recipes) => {
                return (

                    <Link className="recipe-boxes" 
                    href={`/view/${recipes.id}`}
                    key={recipes.id}>
                    <Image 
                        src = {`/recipics/${recipes.image1}`} 
                        alt=""
                        width='200'
                        height='100'
                    />
                    <h5 className="recipetitles">{recipes.Recipe_Name}</h5>
                    </Link>
                );
            })}

            
        </section>


        <div className="button">
          <Link className="viewmore" href="/recipes">View More</Link>
        </div>
      </section>
      
      <section className="section2">
        <div className="container2">
          <div className="heart">
            <Image 
              src= {HEART}
              alt="Heart"
              width='70'
              height='70'
            />
          </div>

          <div className="text-c2">
            <p>"Discover a world of culinary <br />inspiration with The Recipe Room, <br /> your ultimate recipe repository!"</p>
          </div>

          <div className="logo1">
            <Image 
              src={logo1}
              alt="The Recipe Room Logo (1)"
              width='150'
              height='150'
            />
          </div>
        </div>
      </section>

    </>
  );
}

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "./pages/recipe.json");
  const fileContent = fs.readFileSync(filePath, 'utf8');
  const data = JSON.parse(fileContent);

 
  return {
      props: {
          recipe: data,
      },
  };
}