import Head from "next/head";

export default function AboutUs () {
    return (
        <>

        <Head>
        <title>The Recipe Room</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo1.png" />
        </Head>

        
        <div className="description">
            <h1 className="hometitle">About Us</h1>

            <div className="descriptionp">
                <p>Welcome to The Recipe Room - Where Culinary Creations Come to Life!</p>
            </div>
            

        </div>













        </>
    );
}