import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import grilledlemon from '../public/grilledlemon.jpg';
import quinoa from '../public/quinoa.png';
import shrimp from '../public/shrimp.jpg';
import teriyakitofu from '../public/teriyakitofu.jpg'
import salmon from '../public/salmon.jpg'
import HEART from '../public/HEART.png'
import logo1 from '../public/logo1.png'
import spoon from '../public/spoonandfork.png'
import breakfast from '../public/breakfast.jpg'
import lunch from '../public/lunch.jpg'
import salad from '../public/salad.jpg'
import dinner from '../public/dinner.jpg'
import styles from "@/styles/Home.module.css";
import Header from "@/components/constants/Header";
import { Icon } from 'semantic-ui-react'

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>The Recipe Room</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo1.png" />
     
      </Head>
      <section className="section1">

      <div className="container">
        <h1 className="hometitle">Top 10 Recipes</h1>

        <div className="recipes1">
          
          <div className="recipe">
            <Image 
              src={grilledlemon}
              alt="Grilled Lemon Herb Chicken"
              width='200'
              height='150'            
            />
            <h4>Grilled Lemon Herb Chicken</h4>
            <p>You'll love the simple lemon <br />
            marinade on this grilled chicken! <br />
            It's so easy, bright, and flavorful.</p>
          </div>

          <div className="recipe">
            <Image 
              src={quinoa}
              alt="Quinoa and Black Bean Salad"
              width='200'
              height='150'
            />
            <h4>Quinoa and Black Bean Salad</h4>
            <p>This superfood Black Bean <br />
            and Quinoa Salad recipe is one of my <br />
            absolute favorite quick meals to make!</p>
          </div>

          <div className="recipe">
            <Image 
              src={shrimp}
              alt="Shrimp and Avocado Salad"
              width='200'
              height='150'
            />
            <h4>Shrimp and Avocado Salad</h4>
            <p>The simple but totally flavorful <br />
            shrimp salad makes the perfect <br/>
            meal-prep for lunch or dinner!</p>
          </div>

          <div className="recipe">
            <Image 
              src={teriyakitofu}
              alt="Teriyaki Tofu Stir-Fry"
              width='200'
              height='150'
            />
            <h4>Teriyaki Tofu Stir-Fry</h4>
            <p>Deliciously savory and satisfying <br />
            Teriyaki Tofu Stir-Fry blends perfectly <br />
            seasoned tofu with crisp vegetables!</p>
          </div>

          <div className="recipe">
            <Image 
              src={salmon}
              alt="Salmon and Asparagus Foil Packets"
              width='200'
              height='150'
            />
            <h4>Salmon and Asparagus Foil Packets</h4>
            <p>Delicious and healthy, Salmon and <br />
            Asparagus Foil Packets are a simple <br />
            culinary delight!</p>
          </div>

        </div>
      </div>
      
      <div className="button">
      <button id="viewmore" className="viewmore">View More</button>
      </div>
      </section>

      <section className="section2">
        <div className="container2">
          <div className="heart">
            <Image 
              src= {HEART}
              alt="Heart"
              width='70'
              height='70'
            />
          </div>

          <div className="text-c2">
            <p>"Discover a world of culinary <br />inspiration with The Recipe Room, <br /> your ultimate recipe repository!"</p>
          </div>

          <div className="logo1">
            <Image 
              src={logo1}
              alt="The Recipe Room Logo (1)"
              width='150'
              height='150'
            />
          </div>
        </div>
      </section>

      <section id="section3">
        <div className="container3">
          <div className="spoon">
            <Image 
              src = {spoon}
              alt = "Spoon and Fork logo"
              width='70'
              height='70'
            />
          </div>

          <div className="latest">
            <h1 className="latestrecipes">Latest Recipes</h1>

            <div className="categories">
              <div className="category">
                <Image 
                  src ={breakfast}
                  alt = "Breakfast"
                  width='300'
                  height='350'
                />

                <div className="content">
                  <h1>Breakfast</h1>
                  <p>Start your day with a delightful and energizing breakfast experience that awakens your senses and fuels your body for the challenges ahead. Our breakfast offerings are a symphony of flavors, carefully curated to provide a perfect balance of nutrition and indulgence.</p>
                  <button className="viewmore-section3">View More</button>
                </div>
              </div>

              <div className="category">
                <Image 
                  src={lunch}
                  alt="Lunch"
                  width='300'
                  height='350'
                />

                <div className="content">
                  <h1>Lunch</h1>
                  <p>Savor the artistry of our skilled chefs as they <br/> transform simple ingredients into culinary <br/> masterpieces. Whether you're in the mood <br/> for a succulent grilled dish, a hearty pasta creation, <br/> or a light and refreshing wrap, our menu <br/> caters to every  craving and culinary preference.</p>
                  <button className="viewmore-section3">View More</button>
                </div>
              </div>

              <div className="category">
                <Image 
                  src={salad}
                  alt="Salad"
                  width='300'
                  height='350'
                />

                <div className="content">
                  <h1>Salad</h1>
                  <p>Introducing our vibrant and enticing salads that redefine the art of freshness and flavor. Crafted with a meticulous blend of crisp, garden-fresh ingredients, each salad on our menu is a masterpiece designed to elevate your dining experience to new heights.</p>
                  <button className="viewmore-section3">View More</button>
                </div>
              </div>

              <div className="category">
                <Image 
                  src={dinner}
                  alt="Dinner"
                  width='300'
                  height='350'
                />

                <div className="content">
                  <h1>Dinner</h1>
                  <p>Experience an exquisite evening of culinary delight at our dining destination. Our dinner menu invites you to savor a symphony of flavors, expertly crafted to satisfy every palate.</p>    
                  <button className="viewmore-section3">View More</button>
                </div>
              </div>

            </div>
          </div>



        </div>
      </section>

     



  
    </>
  );
}
