import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import grilledlemon from '../public/grilledlemon.jpg';
import quinoa from '../public/quinoa.png';
import shrimp from '../public/shrimp.jpg';
import styles from "@/styles/Home.module.css";
import Header from "@/components/constants/Header";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>The Recipe Room</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo1.png" />
     
      </Head>

      <div className="text-center">
        <h1 className="hometitle">Top 10 Recipes</h1>
        <div className="recipes">
          <div className="recipes1">
            <div className="recipe1">
              <Image
                src={grilledlemon} 
                alt="Grilled Lemon Herb Chicken"
                width='200'
                height='150'
              />

              <h4>Grilled Lemon Herb Chicken</h4>
              <p>You'll love the simple lemon <br />
              marinade on this grilled chicken! <br />
              It's so easy, bright, and flavorful.
            </p>
            </div>

            <div className="recipe2">
              <Image 
                src={quinoa}
                alt="Quinoa Black and Bean Salad"
                width = '200'
                height ='150'
              />

              <h4>Quinoa Black and Bean Salad</h4>
              <p>This Superfood Black Bean & <br />
                Quinoa Salad Recipe is one of my <br />
                absolute favorite quick meals to make...
              </p>
            </div>

            <div className="recipe3">
              <Image 
                src = {shrimp}
                alt="Shrimp and Avocado Salad"
                width='200'
                height ='150'    
              />

              <h4>Shrimp and Avocado Salad</h4>
              <p>
              The simple but totally flavorful <br />
                shrimp salad makes the perfect <br />
                meal-prep for lunch or dinner ..
              </p>



            </div>

            

          </div>

        </div>

      </div>
      
    </>
  );
}
